import type { NextPage } from "next";
import Head from "next/head";

import Footer from "../components/Footer";
import Header from "../components/Header";
import PageBody from "../components/PageBody";
import { getAllPosts, getPostBySlug } from "../lib/api";
import markdownToHtml from "../lib/markdownToHtml";

interface IProps {
  page: {
    page_title: string;
    slug: string;
    content: string;
  };
}

const BasicPage: NextPage<IProps> = ({ page }: IProps) => {
  const title = `Icon - ${page.page_title}`;

  return (
    <div>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <PageBody>
        <h1>{page.page_title}</h1>
        <div dangerouslySetInnerHTML={{ __html: page.content }} />
      </PageBody>
      <Footer />
    </div>
  );
};

type Params = {
  params: {
    slug: string;
  };
};

export async function getStaticProps({ params }: Params) {
  const page = getPostBySlug(params.slug, ["page_title", "slug", "content"]);
  const content = await markdownToHtml(page.content || "");

  console.log(page);

  return {
    props: {
      page: {
        ...page,
        content,
      },
    },
  };
}

export async function getStaticPaths() {
  const posts = getAllPosts(["slug"]);

  return {
    paths: posts.map((post) => {
      return {
        params: {
          slug: post.slug,
        },
      };
    }),
    fallback: false,
  };
}

export default BasicPage;
