import type { NextPage } from "next";
import Head from "next/head";
import AboutPeople from "../components/about/AboutPeople";
import AboutTop from "../components/about/AboutTop";
import Header from "../components/Header";
import HomeBlocks from "../components/home/HomeBlocks";
import HomeTop from "../components/home/HomeTop";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <AboutTop />
      <AboutPeople />
    </div>
  );
};

export default Home;
