import type { NextPage } from "next";
import Head from "next/head";
import BottomBlocks from "../components/about/BottomBlocks";
import AboutPeople from "../components/about/AboutPeople";
import Footer from "../components/Footer";
import Header from "../components/Header";
import PageTop from "../components/PageTop";
import Icon from "../public/images/icon-placeholder.svg";
import BottomText from "../components/BottomText";
import { getSectionBySlug } from "../lib/api";
import { IFooter } from "../types";

interface IProps {
  footer: IFooter;
}

const About: NextPage<IProps> = ({ footer }: IProps) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <PageTop>
        <h1>Building the future, today.</h1>
        <p>
          The <Icon /> ICON Foundation is not the ICON Project. The ICON
          Foundation is a public-benefit, non-profit <Icon /> organization that
          supports open development of decentralized technologies by providing
          financial support and by advising on business and technology
          development practices.
        </p>
      </PageTop>
      <AboutPeople />
      {/* <BottomText />
      <BottomBlocks /> */}
      <Footer footer={footer} />
    </div>
  );
};

export async function getStaticProps() {
  const footer = getSectionBySlug("footer", [
    "copyright_text",
    "navigations",
    "social",
  ]);

  return {
    props: {
      footer,
    },
  };
}

export default About;
