import type { NextPage } from "next";
import Head from "next/head";
import BottomBlocks from "../components/about/BottomBlocks";
import BottomText from "../components/BottomText";
import Footer from "../components/Footer";
import Header from "../components/Header";
import PageTop from "../components/PageTop";
import ProjectsProjects from "../components/projects/ProjectsProjects";
import Icon from "../public/images/icon-placeholder.svg";
import { getPageBySlug } from "../lib/api";
import markdownToHtml from "../lib/markdownToHtml";

interface IProps {
  page: {
    heading: string;
    top_text: string;
    projects: [
      {
        title: string;
        description: string;
        url: string;
        image: string;
      }
    ];
  };
}

const Projects: NextPage<IProps> = ({ page }: IProps) => {
  return (
    <div>
      <Head>
        <title>Icon - Projects</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <PageTop>
        <h1>{page.heading}</h1>
        <div dangerouslySetInnerHTML={{ __html: page.top_text }} />
      </PageTop>
      <ProjectsProjects projects={page.projects} />
      <BottomText />

      <BottomBlocks />
      <Footer />
    </div>
  );
};

export async function getStaticProps() {
  const page = getPageBySlug("projects", [
    "heading",
    "top_text",
    "projects",
    "image",
  ]);
  const top_text = await markdownToHtml(page.top_text || "");

  console.log(page);

  return {
    props: {
      page: {
        ...page,
        top_text,
      },
    },
  };
}

export default Projects;
